### ISSUE TITLE
Command error in documentation 

### ISSUE THREAD

**Issue by bharathkarumudi** [WithSecureLabs/IAMGraph#1]
The `run` command is given two times in the document, and while executing encountered the below error: 

```
Usage: iamgraph run [OPTIONS]
Try 'iamgraph run --help' for help.

Error: No such option: --db-uri
```
The command should be `iamgraph --db-uri bolt://localhost:7687 run --input-dir ./input/`

**Comment by alkall** [comment]
True, there was a typo. I've pushed an update fixing it. Thanks for raising this @bharathkarumudi !
